// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManager.Models;

#nullable disable

namespace TaskManager.Migrations
{
    [DbContext(typeof(TaskManagerDbContext))]
    [Migration("20250617161047_UserPasswordHash")]
    partial class UserPasswordHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.17");

            modelBuilder.Entity("TaskManager.Models.User", b =>
                {
                    b.Property<string>("Login")
                        .HasColumnType("TEXT")
                        .HasColumnName("login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Login")
                        .HasName("pK_users");

                    b.HasIndex("Login")
                        .HasDatabaseName("iX_users_login");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TaskManager.Models.User", b =>
                {
                    b.OwnsOne("TaskManager.Models.PasswordHash", "Password", b1 =>
                        {
                            b1.Property<string>("UserLogin")
                                .HasColumnType("TEXT")
                                .HasColumnName("login");

                            b1.Property<string>("Hash")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("password_Hash");

                            b1.Property<string>("Salt")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("password_Salt");

                            b1.HasKey("UserLogin");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserLogin")
                                .HasConstraintName("fK_users_users_login");
                        });

                    b.Navigation("Password")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
